### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by SimoTheGamer** [arduino/arduino-iot-js#526]
![image](https://github.com/arduino/arduino-iot-js/assets/74712999/e3bea20b-8dfa-49b7-b0bc-a8feac2d7584)

0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\simon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.5.0
2 info using node@v21.6.2
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Users\simon\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\simon\Desktop\PROVA ALEXA + ARDUINO_CLOUD\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\simon\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\simon\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 13ms
17 timing npm:load:configload Completed in 13ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install arduino-iot-js
22 verbose argv "install" "arduino-iot-js"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\Users\simon\AppData\Local\npm-cache\_logs\2024-04-02T08_07_00_409Z-
26 verbose logfile C:\Users\simon\AppData\Local\npm-cache\_logs\2024-04-02T08_07_00_409Z-debug-0.log
27 timing npm:load:logFile Completed in 11ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 1ms
30 timing npm:load Completed in 56ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 2 files
33 timing idealTree:init Completed in 9ms
34 timing idealTree:userRequests Completed in 4ms
35 silly idealTree buildDeps
36 silly fetch manifest arduino-iot-js@*
37 silly logfile done cleaning log files
38 http fetch GET 200 https://registry.npmjs.org/arduino-iot-js 18ms (cache hit)
39 silly placeDep ROOT arduino-iot-js@0.13.0 OK for:  want: *
40 silly fetch manifest @arduino/cbor-js@github:arduino/cbor-js
41 silly fetch manifest jws@^4.0.0
42 silly fetch manifest mqtt@^4.3.7
43 silly fetch manifest node-fetch@^2.6.7
44 silly fetch manifest rxjs@^6.5.5
45 silly fetch manifest whatwg-fetch@^3.0.0
46 http fetch GET 200 https://registry.npmjs.org/mqtt 56ms (cache hit)
47 http fetch GET 200 https://registry.npmjs.org/whatwg-fetch 67ms (cache hit)
48 http fetch GET 200 https://registry.npmjs.org/jws 71ms (cache hit)
49 http fetch GET 200 https://registry.npmjs.org/node-fetch 73ms (cache hit)
50 http fetch GET 200 https://registry.npmjs.org/rxjs 82ms (cache hit)
51 timing idealTree:#root Completed in 129ms
52 silly fetch manifest encoding@^0.1.0
53 http fetch GET 200 https://registry.npmjs.org/encoding 4ms (cache hit)
54 silly placeDep node_modules/arduino-iot-js @arduino/cbor-js@ OK for: arduino-iot-js@0.13.0 want: github:arduino/cbor-js
55 silly placeDep ROOT jws@4.0.0 OK for: arduino-iot-js@0.13.0 want: ^4.0.0
56 silly placeDep ROOT mqtt@4.3.8 OK for: arduino-iot-js@0.13.0 want: ^4.3.7
57 silly placeDep ROOT node-fetch@2.7.0 OK for: arduino-iot-js@0.13.0 want: ^2.6.7
58 silly placeDep ROOT rxjs@6.6.7 OK for: arduino-iot-js@0.13.0 want: ^6.5.5
59 silly placeDep ROOT whatwg-fetch@3.6.20 OK for: arduino-iot-js@0.13.0 want: ^3.0.0
60 silly fetch manifest jwa@^2.0.0
61 silly fetch manifest safe-buffer@^5.0.1
62 silly fetch manifest commist@^1.0.0
63 silly fetch manifest concat-stream@^2.0.0
64 silly fetch manifest debug@^4.1.1
65 silly fetch manifest duplexify@^4.1.1
66 silly fetch manifest help-me@^3.0.0
67 http fetch GET 200 https://registry.npmjs.org/commist 25ms (cache hit)
68 silly fetch manifest inherits@^2.0.3
69 http fetch GET 200 https://registry.npmjs.org/help-me 26ms (cache hit)
70 silly fetch manifest lru-cache@^6.0.0
71 http fetch GET 200 https://registry.npmjs.org/concat-stream 29ms (cache hit)
72 silly fetch manifest minimist@^1.2.5
73 http fetch GET 200 https://registry.npmjs.org/safe-buffer 32ms (cache hit)
74 silly fetch manifest mqtt-packet@^6.8.0
75 http fetch GET 200 https://registry.npmjs.org/jwa 33ms (cache hit)
76 silly fetch manifest number-allocator@^1.0.9
77 http fetch GET 200 https://registry.npmjs.org/duplexify 33ms (cache hit)
78 silly fetch manifest pump@^3.0.0
79 http fetch GET 200 https://registry.npmjs.org/debug 37ms (cache hit)
80 silly fetch manifest readable-stream@^3.6.0
81 http fetch GET 200 https://registry.npmjs.org/mqtt-packet 17ms (cache hit)
82 silly fetch manifest reinterval@^1.1.0
83 http fetch GET 200 https://registry.npmjs.org/inherits 28ms (cache hit)
84 silly fetch manifest rfdc@^1.3.0
85 http fetch GET 200 https://registry.npmjs.org/number-allocator 22ms (cache hit)
86 silly fetch manifest split2@^3.1.0
87 http fetch GET 200 https://registry.npmjs.org/minimist 26ms (cache hit)
88 silly fetch manifest ws@^7.5.5
89 http fetch GET 200 https://registry.npmjs.org/pump 24ms (cache hit)
90 silly fetch manifest xtend@^4.0.2
91 http fetch GET 200 https://registry.npmjs.org/lru-cache 34ms (cache hit)
92 silly fetch manifest whatwg-url@^5.0.0
93 http fetch GET 200 https://registry.npmjs.org/readable-stream 30ms (cache hit)
94 silly fetch manifest tslib@^1.9.0
95 http fetch GET 200 https://registry.npmjs.org/reinterval 29ms (cache hit)
96 http fetch GET 200 https://registry.npmjs.org/rfdc 28ms (cache hit)
97 http fetch GET 200 https://registry.npmjs.org/split2 28ms (cache hit)
98 http fetch GET 200 https://registry.npmjs.org/ws 30ms (cache hit)
99 http fetch GET 200 https://registry.npmjs.org/xtend 35ms (cache hit)
100 http fetch GET 200 https://registry.npmjs.org/whatwg-url 29ms (cache hit)
101 http fetch GET 200 https://registry.npmjs.org/tslib 24ms (cache hit)
102 timing idealTree:node_modules/arduino-iot-js Completed in 121ms
103 silly placeDep ROOT jwa@2.0.0 OK for: jws@4.0.0 want: ^2.0.0
104 silly placeDep ROOT safe-buffer@5.2.1 OK for: jws@4.0.0 want: ^5.0.1
105 silly fetch manifest buffer-equal-constant-time@1.0.1
106 silly fetch manifest ecdsa-sig-formatter@1.0.11
107 http fetch GET 200 https://registry.npmjs.org/ecdsa-sig-formatter 8ms (cache hit)
108 http fetch GET 200 https://registry.npmjs.org/buffer-equal-constant-time 10ms (cache hit)
109 timing idealTree:node_modules/jws Completed in 13ms
110 silly placeDep ROOT buffer-equal-constant-time@1.0.1 OK for: jwa@2.0.0 want: 1.0.1
111 silly placeDep ROOT ecdsa-sig-formatter@1.0.11 OK for: jwa@2.0.0 want: 1.0.11
112 timing idealTree:node_modules/jwa Completed in 2ms
113 timing idealTree:node_modules/buffer-equal-constant-time Completed in 1ms
114 timing idealTree:node_modules/ecdsa-sig-formatter Completed in 0ms
115 silly fetch manifest bufferutil@^4.0.1
116 http fetch GET 200 https://registry.npmjs.org/bufferutil 4ms (cache hit)
117 silly fetch manifest utf-8-validate@^5.0.2
118 http fetch GET 200 https://registry.npmjs.org/utf-8-validate 4ms (cache hit)
119 silly placeDep ROOT commist@1.1.0 OK for: mqtt@4.3.8 want: ^1.0.0
120 silly placeDep ROOT concat-stream@2.0.0 OK for: mqtt@4.3.8 want: ^2.0.0
121 silly placeDep ROOT debug@4.3.4 OK for: mqtt@4.3.8 want: ^4.1.1
122 silly placeDep ROOT duplexify@4.1.3 OK for: mqtt@4.3.8 want: ^4.1.1
123 silly placeDep ROOT help-me@3.0.0 OK for: mqtt@4.3.8 want: ^3.0.0
124 silly placeDep ROOT inherits@2.0.4 OK for: mqtt@4.3.8 want: ^2.0.3
125 silly placeDep ROOT lru-cache@6.0.0 OK for: mqtt@4.3.8 want: ^6.0.0
126 silly placeDep ROOT minimist@1.2.8 OK for: mqtt@4.3.8 want: ^1.2.5
127 silly placeDep ROOT mqtt-packet@6.10.0 OK for: mqtt@4.3.8 want: ^6.8.0
128 silly placeDep ROOT number-allocator@1.0.14 OK for: mqtt@4.3.8 want: ^1.0.9
129 silly placeDep ROOT pump@3.0.0 OK for: mqtt@4.3.8 want: ^3.0.0
130 silly placeDep ROOT readable-stream@3.6.2 OK for: mqtt@4.3.8 want: ^3.6.0
131 silly placeDep ROOT reinterval@1.1.0 OK for: mqtt@4.3.8 want: ^1.1.0
132 silly placeDep ROOT rfdc@1.3.1 OK for: mqtt@4.3.8 want: ^1.3.0
133 silly placeDep ROOT split2@3.2.2 OK for: mqtt@4.3.8 want: ^3.1.0
134 silly placeDep ROOT ws@7.5.9 OK for: mqtt@4.3.8 want: ^7.5.5
135 silly placeDep ROOT xtend@4.0.2 OK for: mqtt@4.3.8 want: ^4.0.2
136 silly fetch manifest leven@^2.1.0
137 silly fetch manifest minimist@^1.1.0
138 silly fetch manifest buffer-from@^1.0.0
139 silly fetch manifest readable-stream@^3.0.2
140 silly fetch manifest typedarray@^0.0.6
141 silly fetch manifest ms@2.1.2
142 silly fetch manifest end-of-stream@^1.4.1
143 silly fetch manifest readable-stream@^3.1.1
144 silly fetch manifest stream-shift@^1.0.2
145 silly fetch manifest glob@^7.1.6
146 http fetch GET 200 https://registry.npmjs.org/leven 16ms (cache hit)
147 silly fetch manifest yallist@^4.0.0
148 http fetch GET 200 https://registry.npmjs.org/buffer-from 18ms (cache hit)
149 silly fetch manifest bl@^4.0.2
150 http fetch GET 200 https://registry.npmjs.org/end-of-stream 17ms (cache hit)
151 silly fetch manifest process-nextick-args@^2.0.1
152 http fetch GET 200 https://registry.npmjs.org/typedarray 21ms (cache hit)
153 silly fetch manifest js-sdsl@4.3.0
154 http fetch GET 200 https://registry.npmjs.org/ms 22ms (cache hit)
155 silly fetch manifest end-of-stream@^1.1.0
156 silly fetch manifest once@^1.3.1
157 http fetch GET 200 https://registry.npmjs.org/glob 21ms (cache hit)
158 silly fetch manifest string_decoder@^1.1.1
159 http fetch GET 200 https://registry.npmjs.org/stream-shift 27ms (cache hit)
160 silly fetch manifest util-deprecate@^1.0.1
161 http fetch GET 200 https://registry.npmjs.org/js-sdsl 21ms (cache hit)
162 http fetch GET 200 https://registry.npmjs.org/yallist 30ms (cache hit)
163 http fetch GET 200 https://registry.npmjs.org/bl 30ms (cache hit)
164 http fetch GET 200 https://registry.npmjs.org/once 27ms (cache hit)
165 http fetch GET 200 https://registry.npmjs.org/string_decoder 21ms (cache hit)
166 http fetch GET 200 https://registry.npmjs.org/process-nextick-args 33ms (cache hit)
167 http fetch GET 200 https://registry.npmjs.org/util-deprecate 22ms (cache hit)
168 timing idealTree:node_modules/mqtt Completed in 87ms
169 silly placeDep ROOT leven@2.1.0 OK for: commist@1.1.0 want: ^2.1.0
170 timing idealTree:node_modules/commist Completed in 1ms
171 silly placeDep ROOT buffer-from@1.1.2 OK for: concat-stream@2.0.0 want: ^1.0.0
172 silly placeDep ROOT typedarray@0.0.6 OK for: concat-stream@2.0.0 want: ^0.0.6
173 timing idealTree:node_modules/concat-stream Completed in 2ms
174 timing idealTree:node_modules/buffer-from Completed in 0ms
175 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
176 timing idealTree:node_modules/debug Completed in 1ms
177 silly placeDep ROOT end-of-stream@1.4.4 OK for: duplexify@4.1.3 want: ^1.4.1
178 silly placeDep ROOT stream-shift@1.0.3 OK for: duplexify@4.1.3 want: ^1.0.2
179 silly fetch manifest once@^1.4.0
180 timing idealTree:node_modules/duplexify Completed in 3ms
181 silly placeDep ROOT once@1.4.0 OK for: end-of-stream@1.4.4 want: ^1.4.0
182 silly fetch manifest wrappy@1
183 http fetch GET 200 https://registry.npmjs.org/wrappy 5ms (cache hit)
184 timing idealTree:node_modules/end-of-stream Completed in 7ms
185 silly placeDep ROOT glob@7.2.3 OK for: help-me@3.0.0 want: ^7.1.6
186 silly fetch manifest fs.realpath@^1.0.0
187 silly fetch manifest inflight@^1.0.4
188 silly fetch manifest minimatch@^3.1.1
189 silly fetch manifest path-is-absolute@^1.0.0
190 http fetch GET 200 https://registry.npmjs.org/fs.realpath 8ms (cache hit)
191 http fetch GET 200 https://registry.npmjs.org/inflight 8ms (cache hit)
192 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 8ms (cache hit)
193 http fetch GET 200 https://registry.npmjs.org/minimatch 9ms (cache hit)
194 timing idealTree:node_modules/help-me Completed in 15ms
195 silly placeDep ROOT fs.realpath@1.0.0 OK for: glob@7.2.3 want: ^1.0.0
196 silly placeDep ROOT inflight@1.0.6 OK for: glob@7.2.3 want: ^1.0.4
197 silly placeDep ROOT minimatch@3.1.2 OK for: glob@7.2.3 want: ^3.1.1
198 silly placeDep ROOT path-is-absolute@1.0.1 OK for: glob@7.2.3 want: ^1.0.0
199 silly fetch manifest brace-expansion@^1.1.7
200 http fetch GET 200 https://registry.npmjs.org/brace-expansion 4ms (cache hit)
201 timing idealTree:node_modules/glob Completed in 10ms
202 timing idealTree:node_modules/fs.realpath Completed in 0ms
203 silly placeDep ROOT wrappy@1.0.2 OK for: inflight@1.0.6 want: 1
204 timing idealTree:node_modules/inflight Completed in 1ms
205 timing idealTree:node_modules/inherits Completed in 0ms
206 timing idealTree:node_modules/leven Completed in 0ms
207 silly placeDep ROOT yallist@4.0.0 OK for: lru-cache@6.0.0 want: ^4.0.0
208 timing idealTree:node_modules/lru-cache Completed in 1ms
209 silly placeDep ROOT brace-expansion@1.1.11 OK for: minimatch@3.1.2 want: ^1.1.7
210 silly fetch manifest balanced-match@^1.0.0
211 silly fetch manifest concat-map@0.0.1
212 http fetch GET 200 https://registry.npmjs.org/concat-map 5ms (cache hit)
213 http fetch GET 200 https://registry.npmjs.org/balanced-match 6ms (cache hit)
214 timing idealTree:node_modules/minimatch Completed in 9ms
215 silly placeDep ROOT balanced-match@1.0.2 OK for: brace-expansion@1.1.11 want: ^1.0.0
216 silly placeDep ROOT concat-map@0.0.1 OK for: brace-expansion@1.1.11 want: 0.0.1
217 timing idealTree:node_modules/brace-expansion Completed in 2ms
218 timing idealTree:node_modules/balanced-match Completed in 0ms
219 timing idealTree:node_modules/concat-map Completed in 0ms
220 timing idealTree:node_modules/minimist Completed in 0ms
221 silly placeDep ROOT bl@4.1.0 OK for: mqtt-packet@6.10.0 want: ^4.0.2
222 silly placeDep ROOT process-nextick-args@2.0.1 OK for: mqtt-packet@6.10.0 want: ^2.0.1
223 silly fetch manifest buffer@^5.5.0
224 http fetch GET 200 https://registry.npmjs.org/buffer 6ms (cache hit)
225 timing idealTree:node_modules/mqtt-packet Completed in 12ms
226 silly placeDep ROOT buffer@5.7.1 OK for: bl@4.1.0 want: ^5.5.0
227 silly fetch manifest base64-js@^1.3.1
228 silly fetch manifest ieee754@^1.1.13
229 http fetch GET 200 https://registry.npmjs.org/ieee754 7ms (cache hit)
230 http fetch GET 200 https://registry.npmjs.org/base64-js 8ms (cache hit)
231 timing idealTree:node_modules/bl Completed in 11ms
232 silly placeDep ROOT base64-js@1.5.1 OK for: buffer@5.7.1 want: ^1.3.1
233 silly placeDep ROOT ieee754@1.2.1 OK for: buffer@5.7.1 want: ^1.1.13
234 timing idealTree:node_modules/buffer Completed in 2ms
235 timing idealTree:node_modules/base64-js Completed in 0ms
236 timing idealTree:node_modules/ieee754 Completed in 0ms
237 timing idealTree:node_modules/ms Completed in 0ms
238 silly placeDep ROOT whatwg-url@5.0.0 OK for: node-fetch@2.7.0 want: ^5.0.0
239 silly fetch manifest tr46@~0.0.3
240 silly fetch manifest webidl-conversions@^3.0.0
241 http fetch GET 200 https://registry.npmjs.org/webidl-conversions 5ms (cache hit)
242 http fetch GET 200 https://registry.npmjs.org/tr46 7ms (cache hit)
243 timing idealTree:node_modules/node-fetch Completed in 9ms
244 silly placeDep ROOT js-sdsl@4.3.0 OK for: number-allocator@1.0.14 want: 4.3.0
245 timing idealTree:node_modules/number-allocator Completed in 1ms
246 timing idealTree:node_modules/js-sdsl Completed in 0ms
247 timing idealTree:node_modules/once Completed in 0ms
248 timing idealTree:node_modules/path-is-absolute Completed in 0ms
249 timing idealTree:node_modules/process-nextick-args Completed in 0ms
250 timing idealTree:node_modules/pump Completed in 0ms
251 silly placeDep ROOT string_decoder@1.3.0 OK for: readable-stream@3.6.2 want: ^1.1.1
252 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@3.6.2 want: ^1.0.1
253 timing idealTree:node_modules/readable-stream Completed in 2ms
254 timing idealTree:node_modules/reinterval Completed in 0ms
255 timing idealTree:node_modules/rfdc Completed in 0ms
256 silly placeDep ROOT tslib@1.14.1 OK for: rxjs@6.6.7 want: ^1.9.0
257 timing idealTree:node_modules/rxjs Completed in 1ms
258 timing idealTree:node_modules/safe-buffer Completed in 0ms
259 timing idealTree:node_modules/split2 Completed in 0ms
260 timing idealTree:node_modules/stream-shift Completed in 0ms
261 timing idealTree:node_modules/string_decoder Completed in 0ms
262 timing idealTree:node_modules/tslib Completed in 0ms
263 timing idealTree:node_modules/typedarray Completed in 0ms
264 timing idealTree:node_modules/util-deprecate Completed in 0ms
265 timing idealTree:node_modules/whatwg-fetch Completed in 0ms
266 silly placeDep ROOT tr46@0.0.3 OK for: whatwg-url@5.0.0 want: ~0.0.3
267 silly placeDep ROOT webidl-conversions@3.0.1 OK for: whatwg-url@5.0.0 want: ^3.0.0
268 timing idealTree:node_modules/whatwg-url Completed in 2ms
269 timing idealTree:node_modules/tr46 Completed in 0ms
270 timing idealTree:node_modules/webidl-conversions Completed in 0ms
271 timing idealTree:node_modules/wrappy Completed in 0ms
272 timing idealTree:node_modules/ws Completed in 0ms
273 timing idealTree:node_modules/xtend Completed in 0ms
274 timing idealTree:node_modules/yallist Completed in 0ms
275 timing idealTree:node_modules/arduino-iot-js/node_modules/@arduino/cbor-js Completed in 0ms
276 timing idealTree:buildDeps Completed in 448ms
277 timing idealTree:fixDepFlags Completed in 1ms
278 timing idealTree Completed in 463ms
279 timing command:install Completed in 473ms
280 verbose stack Error: An unknown git error occurred
280 verbose stack     at makeError (C:\Users\simon\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
280 verbose stack     at C:\Users\simon\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
280 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
281 verbose cwd C:\Users\simon\Desktop\PROVA ALEXA + ARDUINO_CLOUD
282 verbose Windows_NT 10.0.19045
283 verbose node v21.6.2
284 verbose npm  v10.5.0
285 error code ENOENT
286 error syscall spawn git
287 error path git
288 error errno -4058
289 error enoent An unknown git error occurred
290 error enoent This is related to npm not being able to find a file.
290 error enoent
291 verbose exit -4058
292 timing npm Completed in 897ms
293 verbose unfinished npm timer reify 1712045220831
294 verbose unfinished npm timer reify:loadTrees 1712045220837
295 verbose code -4058
296 error A complete log of this run can be found in: C:\Users\simon\AppData\Local\npm-cache\_logs\2024-04-02T08_07_00_409Z-debug-0.log

**Comment by Koiiichi** [comment]
I am facing the same issue here

**Comment by Koiiichi** [comment]
The error you are encountering suggests that the `npm install arduino-iot-js` command is failing because it cannot find Git. The specific error message:

```
npm error code ENOENT
npm error syscall spawn git
npm error path git
npm error errno -4058
npm error enoent An unknown git error occurred
npm error enoent This is related to npm not being able to find a file.
```

indicates that the `npm` process is trying to use Git but cannot find it in the expected path. This usually happens when Git is not installed on your system or the Git executable is not in your system's PATH environment variable.

To resolve this issue, you can follow these steps:

1. **Ensure Git is installed**:
   - If Git is not installed, you can download and install it from the official [Git website](https://git-scm.com/downloads).
   - Follow the installation instructions for your operating system.

2. **Add Git to your system's PATH**:
   - If Git is already installed, ensure that its executable is included in your system's PATH environment variable.
   - You can check this by running `git --version` in your command prompt. If it returns the Git version, then Git is installed and in your PATH. If it returns an error, you need to add Git to your PATH.

3. **Restart your command prompt**:
   - After installing Git or modifying the PATH, you may need to restart your command prompt to apply the changes.

### Detailed Steps to Add Git to PATH (Windows):

1. **Find the Git executable path**:
   - Typically, Git is installed in a directory like `C:\Program Files\Git\bin` or `C:\Program Files (x86)\Git\bin`.

2. **Add the Git path to the system PATH**:
   - Right-click on `This PC` or `Computer` on the desktop or in File Explorer.
   - Click on `Properties`.
   - Click on `Advanced system settings`.
   - In the System Properties window, click on the `Environment Variables` button.
   - In the Environment Variables window, find the `Path` variable in the `System variables` section, select it, and click on `Edit`.
   - In the Edit Environment Variable window, click `New` and add the path to the Git `bin` directory (e.g., `C:\Program Files\Git\bin`).
   - Click `OK` to close all windows.

3. **Verify the installation**:
   - Open a new command prompt and run `git --version` to verify that Git is correctly installed and in the PATH.

After completing these steps, try running `npm install arduino-iot-js` again. The error should be resolved if Git is properly installed and accessible in the PATH.

**Comment by SimoTheGamer** [comment]
Thank you for your answer and for your time.
